model:
<<<<<<< HEAD
  best_model: GradientBoosting
=======
  best_model: RandomForest
>>>>>>> 7de8e4c (Add data processing pipeline and experiment notebooks)
  feature_sets:
    rfe:
    - '0'
    - '2'
    - '3'
    - '4'
    - '5'
    - '9'
    - '12'
    - '13'
    - '14'
    - '15'
<<<<<<< HEAD
  mae: 12639.095902269859
  name: house_price_model
  parameters:
    alpha: 0.9
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.1
    loss: squared_error
    max_depth: 3
    max_features: null
    max_leaf_nodes: null
=======
  mae: 11125.833333333328
  name: house_price_model
  parameters:
    bootstrap: true
    ccp_alpha: 0.0
    criterion: squared_error
    max_depth: 10
    max_features: 1.0
    max_leaf_nodes: null
    max_samples: null
>>>>>>> 7de8e4c (Add data processing pipeline and experiment notebooks)
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
<<<<<<< HEAD
    n_estimators: 100
    n_iter_no_change: null
    random_state: null
    subsample: 1.0
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: false
  r2_score: 0.987080761452518
=======
    monotonic_cst: null
    n_estimators: 150
    n_jobs: null
    oob_score: false
    random_state: null
    verbose: 0
    warm_start: false
  r2_score: 0.992243911394498
>>>>>>> 7de8e4c (Add data processing pipeline and experiment notebooks)
  target_variable: price
